import type { UIColors } from '../colors.ts';
import type { VSCodeTokens } from './VSCodeToken.ts';

import { withAlpha } from '../utils.ts';

export const chat = (colors: UIColors): VSCodeTokens => ({
  'chat.requestBorder': withAlpha(colors.tertiary.foreground, 0.3),
  'chat.requestBackground': colors.unknown,
  'chat.slashCommandBackground': colors.selection.default,
  'chat.slashCommandForeground': colors.tertiary.foreground,

  'chat.avatarBackground': colors.unknown,
  'chat.avatarForeground': colors.unknown,
  'chat.editedFileForeground': colors.primary.foreground,
  'chat.linesAddedForeground': colors.success.foreground,
  'chat.linesRemovedForeground': colors.danger.foreground,
  'chat.requestCodeBorder': colors.unknown,
  'chat.requestBubbleBackground': colors.secondary.foreground,
  'chat.requestBubbleHoverBackground': colors.info.background,
  'chat.checkpointSeparator': colors.foreground.muted,
  'chat.thinkingShimmer': colors.tertiary.foreground,
  'chatManagement.sashBorder': colors.border.default,

  'agents.background': colors.background.default,
  'agentsPanel.background': colors.background.elevated,
  'agentsPanel.foreground': colors.foreground.default,
  'agentsPanel.border': colors.border.default,
  'agentsCard.border': colors.border.default,
  'agentsBottomPanel.border': colors.border.default,
  'agentsGradient.tintColor': withAlpha(colors.tertiary.foreground, 0.2),
  'agentFeedbackEditorWidget.background': colors.background.elevated,
  'agentFeedbackEditorWidget.border': colors.border.default,
  'agentFeedbackInputWidget.border': colors.border.default,
  'agentsUpdateButton.downloadingBackground': colors.info.background,
  'agentsUpdateButton.downloadedBackground': colors.success.background,
  'agentsChatInput.background': colors.background.focus,
  'agentsChatInput.foreground': colors.foreground.default,
  'agentsChatInput.border': colors.border.default,
  'agentsChatInput.focusBorder': colors.primary.foreground,
  'agentsChatInput.placeholderForeground': colors.foreground.muted,
  'agentsNewSessionButton.background': colors.primary.foreground,
  'agentsNewSessionButton.foreground': colors.primary.onForeground,
  'agentsNewSessionButton.border': colors.transparent,
  'agentsNewSessionButton.hoverBackground': colors.primary.hover,
  'agentsBadge.background': colors.secondary.foreground,
  'agentsBadge.foreground': colors.secondary.onForeground,
  'agentsUnreadBadge.background': colors.primary.foreground,
  'agentsUnreadBadge.foreground': colors.primary.onForeground,
  'activeSessionView.background': colors.background.focus,
  'activeSessionView.foreground': colors.foreground.default,
  'inactiveSessionView.background': colors.background.default,
  'inactiveSessionView.foreground': colors.foreground.support,
  'agentsMobileDiff.addedForeground': colors.success.foreground,
  'agentsMobileDiff.modifiedForeground': colors.warning.foreground,
  'agentsMobileDiff.deletedForeground': colors.danger.foreground,
  'agentSessionReadIndicator.foreground': colors.foreground.muted,
  'agentSessionSelectedBadge.border': colors.primary.foreground,
  'agentSessionSelectedUnfocusedBadge.border': colors.border.muted,
  'agentStatusIndicator.background': colors.primary.foreground,
  'aiCustomizationManagement.sashBorder': colors.border.default,

  'inlineChat.background': colors.unknown,
  'inlineChat.foreground': colors.unknown,
  'inlineChat.border': colors.transparent,
  'inlineChat.shadow': colors.transparent,
  'inlineChatInput.border': colors.border.default,
  'inlineChatInput.focusBorder': colors.danger.foreground,
  'inlineChatInput.placeholderForeground': colors.danger.foreground,
  'inlineChatInput.background': colors.danger.foreground,
  'inlineChatDiff.inserted': colors.unknown,
  'inlineChatDiff.removed': colors.unknown,

  'interactive.activeCodeBorder': colors.unknown,
  'interactive.inactiveCodeBorder': colors.unknown,
});
