import type { UIColor } from './UIColor.ts';

import { Foregrounds, UIColors } from '../colors.ts';

export const debug: UIColor = {
  'debugToolBar.background': UIColors.BackgroundElevated,
  'debugToolBar.border': UIColors.Border,
  'editor.stackFrameHighlightBackground': UIColors.BackgroundWarning,
  'editor.focusedStackFrameHighlightBackground': false,
  'editor.inlineValuesForeground': false,
  'editor.inlineValuesBackground': false,
  'debugView.exceptionLabelForeground': false,
  'debugView.exceptionLabelBackground': false,
  'debugView.stateLabelForeground': Foregrounds.Muted,
  'debugView.stateLabelBackground': UIColors.Transparent,
  'debugView.valueChangedHighlight': UIColors.SelectionFound,
  'debugTokenExpression.name': UIColors.Foreground,
  'debugTokenExpression.value': Foregrounds.Muted,
  'debugTokenExpression.string': Foregrounds.Green,
  'debugTokenExpression.boolean': Foregrounds.Blue,
  'debugTokenExpression.number': Foregrounds.Magenta,
  'debugTokenExpression.error': Foregrounds.Red,
  'debugTokenExpression.type': Foregrounds.Muted,

  'debugIcon.breakpointForeground': UIColors.Danger,
  'debugIcon.breakpointDisabledForeground': UIColors.BackgroundDangerFocus,
  'debugIcon.breakpointUnverifiedForeground': UIColors.BackgroundWarningFocus,
  'debugIcon.breakpointCurrentStackframeForeground': UIColors.Warning,
  'debugIcon.breakpointStackframeForeground': UIColors.Unknown,
  'debugIcon.startForeground': UIColors.Success,
  'debugIcon.pauseForeground': UIColors.Warning,
  'debugIcon.stopForeground': UIColors.Danger,
  'debugIcon.disconnectForeground': UIColors.Danger,
  'debugIcon.restartForeground': UIColors.Warning,
  'debugIcon.stepOverForeground': Foregrounds.Support,
  'debugIcon.stepIntoForeground': Foregrounds.Support,
  'debugIcon.stepOutForeground': Foregrounds.Support,
  'debugIcon.continueForeground': UIColors.Success,
  'debugIcon.stepBackForeground': UIColors.Warning,

  'debugConsole.infoForeground': Foregrounds.Muted,
  'debugConsole.warningForeground': UIColors.Warning,
  'debugConsole.errorForeground': UIColors.Danger,
  'debugConsole.sourceForeground': UIColors.Link,
  'debugConsoleInputIcon.foreground': UIColors.Unknown,
};
