import type { UIColor } from './UIColor.ts';

import { Foregrounds, UIColors, withAlpha } from '../colors.ts';

export const editor: UIColor = {
  'scrollbar.shadow': UIColors.Transparent,
  'scrollbarSlider.activeBackground': UIColors.BackgroundFocus,
  'scrollbarSlider.background': UIColors.BackgroundFocus,
  'scrollbarSlider.hoverBackground': UIColors.BackgroundHover,

  'badge.background': UIColors.Secondary,
  'badge.foreground': Foregrounds.OnSecondary,

  'activityBarBadge.background': UIColors.Secondary,
  'activityBarBadge.foreground': Foregrounds.OnSecondary,

  'editor.background': UIColors.Background,
  'editor.foreground': UIColors.Foreground,

  'editorLineNumber.foreground': Foregrounds.Muted,
  'editorLineNumber.activeForeground': UIColors.Foreground,
  'editorLineNumber.dimmedForeground': Foregrounds.Muted,
  'editorCursor.background': UIColors.Background,
  'editorCursor.foreground': UIColors.Foreground,

  'editorMultiCursor.primary.foreground': UIColors.Foreground,
  'editorMultiCursor.primary.background': UIColors.Background,
  'editorMultiCursor.secondary.foreground': UIColors.Tertiary,
  'editorMultiCursor.secondary.background': Foregrounds.OnTertiary,

  'editor.placeholder.foreground': UIColors.BorderMuted,
  'editor.compositionBorder': false,
  'editor.selectionBackground': UIColors.BackgroundFocus,
  'editor.selectionForeground': UIColors.Foreground,

  'editor.inactiveSelectionBackground': UIColors.SelectionInactive,
  'editor.selectionHighlightBackground': UIColors.SelectionInactive,

  'editor.selectionHighlightBorder': UIColors.Transparent,
  'editor.wordHighlightTextBackground': UIColors.SelectionInactive,
  'editor.wordHighlightTextBorder': UIColors.Transparent,

  'editor.findMatchBackground': UIColors.BackgroundHover,
  'editor.findMatchForeground': false,
  'editor.findMatchBorder': UIColors.Transparent,
  'editor.findMatchHighlightForeground': false,
  'editor.findRangeHighlightBackground': UIColors.Foreground,
  'editor.findMatchHighlightBorder': UIColors.Transparent,
  'editor.findMatchHighlightBackground': UIColors.SelectionFound,

  'editor.wordHighlightBackground': UIColors.Selection,
  'editor.wordHighlightStrongBackground': UIColors.Selection,
  'editor.wordHighlightStrongBorder': UIColors.Transparent,
  'editor.wordHighlightBorder': UIColors.Transparent,

  'editor.findRangeHighlightBorder': UIColors.Transparent,
  'search.resultsInfoForeground': Foregrounds.Muted,
  'searchEditor.findMatchBackground': false,
  'searchEditor.findMatchBorder': false,
  'searchEditor.textInputBorder': UIColors.Border,
  'editor.hoverHighlightBackground': UIColors.BackgroundFocus,
  'editor.lineHighlightBackground': UIColors.BackgroundOverlay,
  'editor.lineHighlightBorder': UIColors.Transparent,
  'editor.rangeHighlightBackground': UIColors.BackgroundOverlay,
  'editor.rangeHighlightBorder': UIColors.Transparent,

  'editorWatermark.foreground': false,
  'editorUnicodeHighlight.border': UIColors.Tertiary,
  'editorUnicodeHighlight.background': UIColors.Transparent,

  'editorLink.activeForeground': UIColors.Link,
  'editor.symbolHighlightBackground': UIColors.Transparent,
  'editor.symbolHighlightBorder': UIColors.TertiaryForeground,

  'editorWhitespace.foreground': UIColors.Selection,

  'editorIndentGuide.background1': UIColors.Selection,
  'editorIndentGuide.background2': false,
  'editorIndentGuide.background3': false,
  'editorIndentGuide.background4': false,
  'editorIndentGuide.background5': false,
  'editorIndentGuide.background6': false,

  'editorIndentGuide.activeBackground1': Foregrounds.Support,
  'editorIndentGuide.activeBackground2': false,
  'editorIndentGuide.activeBackground3': false,
  'editorIndentGuide.activeBackground4': false,
  'editorIndentGuide.activeBackground5': false,
  'editorIndentGuide.activeBackground6': false,

  'editorInlayHint.background': UIColors.Transparent,
  'editorInlayHint.foreground': Foregrounds.Muted,
  'editorInlayHint.typeForeground': withAlpha(Foregrounds.Magenta, 0.7),
  'editorInlayHint.typeBackground': UIColors.Transparent,
  'editorInlayHint.parameterForeground': Foregrounds.Muted,
  'editorInlayHint.parameterBackground': UIColors.Transparent,

  'editorRuler.foreground': UIColors.Border,
  'editor.linkedEditingBackground': withAlpha(UIColors.Tertiary, 0.1),

  'editorCodeLens.foreground': Foregrounds.Muted,
  'editorLightBulb.foreground': Foregrounds.Magenta,
  'editorLightBulbAutoFix.foreground': Foregrounds.Yellow,
  'editorLightBulbAi.foreground': Foregrounds.Magenta,
  'editorBracketMatch.background': withAlpha(UIColors.Tertiary, 0.1),
  'editorBracketMatch.border': UIColors.Transparent,

  'editorBracketPairGuide.activeBackground1': false,
  'editorBracketPairGuide.activeBackground2': false,
  'editorBracketPairGuide.activeBackground3': false,
  'editorBracketPairGuide.activeBackground4': false,
  'editorBracketPairGuide.activeBackground5': false,
  'editorBracketPairGuide.activeBackground6': false,
  'editorBracketPairGuide.background1': false,
  'editorBracketPairGuide.background2': false,
  'editorBracketPairGuide.background3': false,
  'editorBracketPairGuide.background4': false,
  'editorBracketPairGuide.background5': false,
  'editorBracketPairGuide.background6': false,

  'editor.foldBackground': UIColors.Transparent,
  'editor.foldPlaceholderForeground': Foregrounds.Muted,
  'editorOverviewRuler.background': UIColors.BackgroundOverlay,
  'editorOverviewRuler.border': UIColors.Border,
  'editorOverviewRuler.findMatchForeground': withAlpha(
    UIColors.Foreground,
    0.5,
  ),
  'editorOverviewRuler.rangeHighlightForeground': UIColors.BackgroundFocus,
  'editorOverviewRuler.selectionHighlightForeground': false,
  'editorOverviewRuler.wordHighlightForeground': UIColors.SelectionFound,
  'editorOverviewRuler.wordHighlightStrongForeground': UIColors.Info,
  'editorOverviewRuler.wordHighlightTextForeground': false,
  'editorOverviewRuler.errorForeground': UIColors.Danger,
  'editorOverviewRuler.warningForeground': UIColors.Warning,
  'editorOverviewRuler.infoForeground': UIColors.Info,
  'editorOverviewRuler.bracketMatchForeground': withAlpha(
    UIColors.Foreground,
    0.5,
  ),
  'editorError.foreground': UIColors.Danger,
  'editorError.border': UIColors.Transparent,
  'editorError.background': UIColors.Transparent,

  'editorWarning.foreground': UIColors.Warning,
  'editorWarning.border': UIColors.Transparent,
  'editorWarning.background': UIColors.Transparent,

  'editorInfo.foreground': UIColors.Info,
  'editorInfo.border': UIColors.Transparent,
  'editorInfo.background': UIColors.Transparent,

  'editorHint.foreground': UIColors.Unknown,
  'editorHint.border': UIColors.Transparent,

  'problemsErrorIcon.foreground': UIColors.Danger,
  'problemsWarningIcon.foreground': UIColors.Warning,
  'problemsInfoIcon.foreground': UIColors.Info,

  'editorUnnecessaryCode.border': UIColors.Transparent,
  'editorUnnecessaryCode.opacity': withAlpha(UIColors.Background, 0.6),
  'editorGutter.background': UIColors.Transparent,

  'editorGutter.foldingControlForeground': Foregrounds.Support,
  'editorGutter.itemGlyphForeground': Foregrounds.Support,
  'editorGutter.itemBackground': UIColors.Transparent,

  'editorCommentsWidget.resolvedBorder': UIColors.Border,
  'editorCommentsWidget.unresolvedBorder': UIColors.Primary,
  'editorCommentsWidget.rangeBackground': UIColors.SelectionFound,
  'editorCommentsWidget.rangeActiveBackground': UIColors.Transparent,
  'editorCommentsWidget.replyInputBackground': UIColors.BackgroundFocus,

  'inlineEdit.gutterIndicator.primaryBorder': UIColors.Transparent,
  'inlineEdit.gutterIndicator.primaryForeground': Foregrounds.OnTertiary,
  'inlineEdit.gutterIndicator.primaryBackground': UIColors.Tertiary,
  'inlineEdit.gutterIndicator.secondaryBorder': UIColors.Transparent,
  'inlineEdit.gutterIndicator.secondaryForeground': Foregrounds.OnSecondary,
  'inlineEdit.gutterIndicator.secondaryBackground': UIColors.Secondary,
  'inlineEdit.gutterIndicator.successfulBorder': UIColors.Transparent,
  'inlineEdit.gutterIndicator.successfulForeground': Foregrounds.OnSuccess,
  'inlineEdit.gutterIndicator.successfulBackground': UIColors.Success,
  'inlineEdit.gutterIndicator.background': UIColors.Selection,

  'inlineEdit.originalBackground': UIColors.Selection,
  'inlineEdit.modifiedBackground': withAlpha(UIColors.Danger, 0.5),
  'inlineEdit.originalChangedLineBackground': false,
  'inlineEdit.originalChangedTextBackground': withAlpha(UIColors.Danger, 0.3),
  'inlineEdit.modifiedChangedLineBackground': withAlpha(UIColors.Success, 0.3),
  'inlineEdit.modifiedChangedTextBackground': withAlpha(UIColors.Success, 0.3),
  'inlineEdit.originalBorder': UIColors.Transparent,
  'inlineEdit.modifiedBorder': UIColors.Transparent,
  'inlineEdit.tabWillAcceptModifiedBorder': UIColors.Success,
  'inlineEdit.tabWillAcceptOriginalBorder': UIColors.Border,
};
