import type { UIColors } from '../colors.ts';
import type { VSCodeTokens } from './VSCodeToken.ts';

export const symbol = (_colors: UIColors): VSCodeTokens => ({
  'symbolIcon.arrayForeground': false,
  'symbolIcon.booleanForeground': false,
  'symbolIcon.classForeground': false,
  'symbolIcon.colorForeground': false,
  'symbolIcon.constantForeground': false,
  'symbolIcon.constructorForeground': false,
  'symbolIcon.enumeratorForeground': false,
  'symbolIcon.enumeratorMemberForeground': false,
  'symbolIcon.eventForeground': false,
  'symbolIcon.fieldForeground': false,
  'symbolIcon.fileForeground': false,
  'symbolIcon.folderForeground': false,
  'symbolIcon.functionForeground': false,
  'symbolIcon.interfaceForeground': false,
  'symbolIcon.keyForeground': false,
  'symbolIcon.keywordForeground': false,
  'symbolIcon.methodForeground': false,
  'symbolIcon.moduleForeground': false,
  'symbolIcon.namespaceForeground': false,
  'symbolIcon.nullForeground': false,
  'symbolIcon.numberForeground': false,
  'symbolIcon.objectForeground': false,
  'symbolIcon.operatorForeground': false,
  'symbolIcon.packageForeground': false,
  'symbolIcon.propertyForeground': false,
  'symbolIcon.referenceForeground': false,
  'symbolIcon.snippetForeground': false,
  'symbolIcon.stringForeground': false,
  'symbolIcon.structForeground': false,
  'symbolIcon.textForeground': false,
  'symbolIcon.typeParameterForeground': false,
  'symbolIcon.unitForeground': false,
  'symbolIcon.variableForeground': false,
});
