import type { UIColors } from '../colors.ts';
import type { VSCodeTokens } from './VSCodeToken.ts';

export const tabs = (colors: UIColors): VSCodeTokens => ({
  'editorGroup.border': colors.border.default,
  'editorGroup.dropBackground': colors.background.overlay,
  'editorGroupHeader.noTabsBackground': colors.transparent,
  'editorGroupHeader.tabsBackground': colors.transparent,
  'editorGroupHeader.tabsBorder': colors.border.default,
  'editorGroupHeader.border': colors.border.default,
  'editorGroup.emptyBackground': colors.transparent,
  'editorGroup.focusedEmptyBorder': colors.border.default,
  'editorGroup.dropIntoPromptForeground': colors.primary.foreground,
  'editorGroup.dropIntoPromptBackground': colors.background.elevated,
  'editorGroup.dropIntoPromptBorder': colors.transparent,
  'tab.activeBackground': colors.background.focus,
  'tab.unfocusedActiveBackground': colors.background.overlay,
  'tab.activeForeground': colors.foreground.default,
  'tab.border': colors.border.default,
  'tab.activeBorder': colors.border.default,
  'tab.selectedBorderTop': colors.border.default,
  'tab.selectedBackground': false,
  'tab.selectedForeground': false,
  'tab.dragAndDropBorder': colors.primary.foreground,
  'tab.unfocusedActiveBorder': colors.border.default,
  'tab.activeBorderTop': colors.border.default,
  'tab.unfocusedActiveBorderTop': colors.border.default,
  'tab.lastPinnedBorder': false,
  'tab.inactiveBackground': colors.transparent,
  'tab.unfocusedInactiveBackground': colors.transparent,
  'tab.inactiveForeground': colors.foreground.support,
  'tab.unfocusedActiveForeground': colors.foreground.support,
  'tab.unfocusedInactiveForeground': colors.foreground.support,
  'tab.hoverBackground': colors.background.hover,
  'tab.unfocusedHoverBackground': colors.background.hover,
  'tab.hoverForeground': false,
  'tab.unfocusedHoverForeground': false,
  'tab.hoverBorder': false,
  'tab.unfocusedHoverBorder': false,
  'tab.activeModifiedBorder': false,
  'tab.inactiveModifiedBorder': false,
  'tab.unfocusedActiveModifiedBorder': false,
  'tab.unfocusedInactiveModifiedBorder': colors.danger.foreground,
  'editorPane.background': colors.transparent,
  'sideBySideEditor.horizontalBorder': colors.border.default,
  'sideBySideEditor.verticalBorder': colors.border.default,
});
