import type { UIColor } from './UIColor.ts';

import { Foregrounds, UIColors } from '../colors.ts';

export const tabs: UIColor = {
  'editorGroup.border': UIColors.Border,
  'editorGroup.dropBackground': UIColors.BackgroundOverlay,
  'editorGroupHeader.noTabsBackground': UIColors.Transparent,
  'editorGroupHeader.tabsBackground': UIColors.Transparent,
  'editorGroupHeader.tabsBorder': UIColors.Border,
  'editorGroupHeader.border': UIColors.Border,
  'editorGroup.emptyBackground': UIColors.Transparent,
  'editorGroup.focusedEmptyBorder': UIColors.Border,
  'editorGroup.dropIntoPromptForeground': UIColors.Primary,
  'editorGroup.dropIntoPromptBackground': UIColors.BackgroundElevated,
  'editorGroup.dropIntoPromptBorder': UIColors.Transparent,
  'tab.activeBackground': UIColors.BackgroundFocus,
  'tab.unfocusedActiveBackground': UIColors.BackgroundOverlay,
  'tab.activeForeground': UIColors.Foreground,
  'tab.border': UIColors.Border,
  'tab.activeBorder': UIColors.Border,
  'tab.selectedBorderTop': UIColors.Border,
  'tab.selectedBackground': false,
  'tab.selectedForeground': false,
  'tab.dragAndDropBorder': UIColors.Primary,
  'tab.unfocusedActiveBorder': UIColors.Border,
  'tab.activeBorderTop': UIColors.Border,
  'tab.unfocusedActiveBorderTop': UIColors.Border,
  'tab.lastPinnedBorder': false,
  'tab.inactiveBackground': UIColors.Transparent,
  'tab.unfocusedInactiveBackground': UIColors.Transparent,
  'tab.inactiveForeground': Foregrounds.Support,
  'tab.unfocusedActiveForeground': Foregrounds.Support,
  'tab.unfocusedInactiveForeground': Foregrounds.Support,
  'tab.hoverBackground': UIColors.BackgroundHover,
  'tab.unfocusedHoverBackground': UIColors.BackgroundHover,
  'tab.hoverForeground': false,
  'tab.unfocusedHoverForeground': false,
  'tab.hoverBorder': false,
  'tab.unfocusedHoverBorder': false,
  'tab.activeModifiedBorder': false,
  'tab.inactiveModifiedBorder': false,
  'tab.unfocusedActiveModifiedBorder': false,
  'tab.unfocusedInactiveModifiedBorder': UIColors.Danger,
  'editorPane.background': UIColors.Transparent,
  'sideBySideEditor.horizontalBorder': UIColors.Border,
  'sideBySideEditor.verticalBorder': UIColors.Border,
};
