import type { UIColors } from '../colors.ts';
import type { VSCodeTokens } from './VSCodeToken.ts';

export const test = (colors: UIColors): VSCodeTokens => ({
  'testing.runAction': colors.success.foreground,
  'testing.iconErrored': colors.danger.foreground,
  'testing.iconFailed': colors.danger.foreground,
  'testing.iconPassed': colors.success.foreground,
  'testing.iconQueued': colors.foreground.support,
  'testing.iconUnset': colors.foreground.muted,
  'testing.iconSkipped': colors.foreground.muted,
  'testing.iconErrored.retired': colors.danger.foreground,
  'testing.iconFailed.retired': colors.danger.foreground,
  'testing.iconPassed.retired': colors.success.foreground,
  'testing.iconQueued.retired': colors.foreground.support,
  'testing.iconUnset.retired': colors.foreground.muted,
  'testing.iconSkipped.retired': colors.foreground.muted,
  'testing.peekBorder': false,
  'testing.peekHeaderBackground': false,
  'testing.message.error.lineBackground': false,
  'testing.message.info.decorationForeground': false,
  'testing.message.info.lineBackground': false,
  'testing.messagePeekBorder': false,
  'testing.messagePeekHeaderBackground': false,

  'testing.coveredBackground': colors.success.background,
  'testing.coveredBorder': colors.transparent,
  'testing.coveredGutterBackground': colors.success.background,
  'testing.uncoveredBranchBackground': colors.warning.background,
  'testing.uncoveredBackground': colors.danger.background,
  'testing.uncoveredBorder': colors.transparent,
  'testing.uncoveredGutterBackground': colors.danger.background,
  'testing.coverCountBadgeBackground': colors.success.foreground,
  'testing.coverCountBadgeForeground': colors.success.onForeground,
  'testing.message.error.badgeBackground': colors.danger.foreground,
  'testing.message.error.badgeBorder': colors.transparent,
  'testing.message.error.badgeForeground': colors.danger.onForeground,
});
